import pino, { type DestinationStream, type Logger } from 'pino';

const REDACTED = '[REDACTED]';

export function createLogger(level: string, destination?: DestinationStream): Logger {
  const options = {
    base: {
      service: 'craftlogin',
    },
    level,
    redact: {
      censor: REDACTED,
      paths: [
        '*.accessToken',
        '*.access_token',
        '*.authorizationCode',
        '*.authorization',
        '*.clientSecret',
        '*.client_secret',
        '*.csrfToken',
        '*.x-csrf-token',
        '*.code',
        '*.cookie',
        '*.idToken',
        '*.id_token',
        '*.codeVerifier',
        '*.minecraftAccessToken',
        '*.microsoftAccessToken',
        '*.password',
        '*.refreshToken',
        '*.refresh_token',
        '*.RpsTicket',
        '*.secret',
        '*.serverHost',
        '*.state',
        '*.token',
        '*.Token',
        '*.identityToken',
        '*.uhs',
        '*.userHash',
        '*.verificationCode',
        '*.xboxLiveToken',
        '*.xstsToken',
        'accessToken',
        'access_token',
        'authorizationCode',
        'authorization',
        'clientSecret',
        'client_secret',
        'csrfToken',
        'code',
        'codeVerifier',
        'cookie',
        'headers.authorization',
        'headers.cookie',
        'headers.x-csrf-token',
        'idToken',
        'id_token',
        'minecraftAccessToken',
        'microsoftAccessToken',
        'password',
        'query',
        'refreshToken',
        'refresh_token',
        'RpsTicket',
        'req.headers.authorization',
        'req.headers.cookie',
        'req.headers.x-csrf-token',
        'req.body',
        'req.query',
        'req.url',
        'request.body',
        'request.query',
        'request.url',
        'secret',
        'serverHost',
        'state',
        'token',
        'Token',
        'identityToken',
        'uhs',
        'url',
        'userHash',
        'verificationCode',
        'xboxLiveToken',
        'xstsToken',
      ],
    },
  };
  return destination === undefined ? pino(options) : pino(options, destination);
}
